name: agron_gcs
description: A Ground Control Station application for agricultural drones.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_map: ^6.1.0
  flutter_map_location_marker: ^8.0.2
  geolocator: ^10.1.0
  latlong2: ^0.9.1
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  http: ^1.1.0
  socket_io_client: ^2.0.3+1
  path_provider: ^2.1.0
  sqflite: ^2.3.0
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.1
  permission_handler: ^11.0.1
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - AgronLogos/ 

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive:
    android: true
    ios: true
    foreground_image: "assets/icon/app_icon_foreground.png"
    background_color: "#FFFFFF" 