// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKODWxUdJUMJsB57YKP4lOANwWVUJysX0',
    appId: '1:422258555626:web:ebec04b5d36689e0163593',
    messagingSenderId: '422258555626',
    projectId: 'agron-dashboard',
    authDomain: 'agron-dashboard.firebaseapp.com',
    storageBucket: 'agron-dashboard.firebasestorage.app',
    measurementId: 'G-BKCE35QP9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABtMZJAzxACtpAKqu00RCOhyDFjiEmGnk',
    appId: '1:422258555626:android:5724d02e2f25bf63163593',
    messagingSenderId: '422258555626',
    projectId: 'agron-dashboard',
    storageBucket: 'agron-dashboard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA60I3lI7s2oj7AxcoGFbEs1b51olKWTM',
    appId: '1:422258555626:ios:1d3ddf7f2ae36596163593',
    messagingSenderId: '422258555626',
    projectId: 'agron-dashboard',
    storageBucket: 'agron-dashboard.firebasestorage.app',
    iosBundleId: 'com.example.agronGcs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA60I3lI7s2oj7AxcoGFbEs1b51olKWTM',
    appId: '1:422258555626:ios:1d3ddf7f2ae36596163593',
    messagingSenderId: '422258555626',
    projectId: 'agron-dashboard',
    storageBucket: 'agron-dashboard.firebasestorage.app',
    iosBundleId: 'com.example.agronGcs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKODWxUdJUMJsB57YKP4lOANwWVUJysX0',
    appId: '1:422258555626:web:40963e1e24ddf0bb163593',
    messagingSenderId: '422258555626',
    projectId: 'agron-dashboard',
    authDomain: 'agron-dashboard.firebaseapp.com',
    storageBucket: 'agron-dashboard.firebasestorage.app',
    measurementId: 'G-Z8SY50N6NW',
  );
}
