import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // <- generated by flutterfire
import 'package:agron_gcs/screens/auth/login_screen.dart';
import 'package:agron_gcs/screens/auth/signup_screen.dart';
import 'package:agron_gcs/screens/home/home_screen.dart';
import 'package:agron_gcs/screens/mission_screen.dart';
import 'package:agron_gcs/screens/chat_screen.dart';
import 'package:agron_gcs/screens/profile_screen.dart';
import 'package:agron_gcs/providers/auth_provider.dart';
import 'package:agron_gcs/services/drone_service.dart';
import 'package:agron_gcs/theme/app_theme.dart';
import 'package:agron_gcs/services/mission_services.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
    ChangeNotifierProvider(create: (_) => AuthProvider()),

    ChangeNotifierProvider<DroneService>(
      create: (_) {
        final service = DroneService();
        service.initialize();
        return service;
      },
    ),

    Provider(create: (_) => MissionService()),  // <-- ADD THIS
  ],

      child: MaterialApp(
        title: 'Agron GCS',
        theme: AppTheme.lightTheme,
        darkTheme: AppTheme.darkTheme,
        themeMode: ThemeMode.system,
        home: const SplashScreen(),
        routes: {
          '/login': (context) => const LoginScreen(),
          '/signup': (context) => const SignUpScreen(),
          '/home': (context) => const HomeScreen(),
          '/missions': (context) => const MissionScreen(),
          '/chat': (context) => const ChatScreen(),
          '/profile': (context) => const ProfileScreen(),
        },
        debugShowCheckedModeBanner: false,
      ),
    );
  }
}

/// SplashScreen checks auth status and navigates accordingly
class SplashScreen extends StatefulWidget {
  const SplashScreen({super.key});

  @override
  State<SplashScreen> createState() => _SplashScreenState();
}

class _SplashScreenState extends State<SplashScreen> {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
    _checkAuthAndNavigate();
    });
  }

  Future<void> _checkAuthAndNavigate() async {
    final authProvider = Provider.of<AuthProvider>(context, listen: false);
    await authProvider.checkAuthStatus(); // checks Firebase login
    if (!mounted) return;

    if (authProvider.isAuthenticated) {
      Navigator.pushReplacementNamed(context, '/home');
    } else {
      Navigator.pushReplacementNamed(context, '/login');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Theme.of(context).scaffoldBackgroundColor,
      body: Center(
        child: SvgPicture.asset(
          Theme.of(context).brightness == Brightness.light
              ? 'AgronLogos/Brand-logo-black.svg'
              : 'AgronLogos/Brand-logo-white.svg',
          width: 200,
          height: 200,
          placeholderBuilder: (context) => const Center(
            child: CircularProgressIndicator(),
          ),
        ),
      ),
    );
  }
}
